//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.22 at 10:01:12 AM PDT 
//


package com.sendori.testcenter.xsd;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Build"/>
 *         &lt;element ref="{}HostInfo"/>
 *         &lt;element ref="{}RankModel"/>
 *         &lt;element ref="{}FeedAndSubPublisherInformation"/>
 *         &lt;element ref="{}BackfillIndexData"/>
 *         &lt;element ref="{}DirectAdService"/>
 *         &lt;element ref="{}Backfills"/>
 *         &lt;element ref="{}RequestHeaders"/>
 *         &lt;element ref="{}ApplicationResponseTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "build",
    "hostInfo",
    "rankModel",
    "feedAndSubPublisherInformation",
    "backfillIndexData",
    "directAdService",
    "backfills",
    "requestHeaders",
    "applicationResponseTime"
})
@XmlRootElement(name = "Debug")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Debug {

    @XmlElement(name = "Build", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected Build build;
    @XmlElement(name = "HostInfo", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected HostInfo hostInfo;
    @XmlElement(name = "RankModel", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected RankModel rankModel;
    @XmlElement(name = "FeedAndSubPublisherInformation", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected FeedAndSubPublisherInformation feedAndSubPublisherInformation;
    @XmlElement(name = "BackfillIndexData", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected BackfillIndexData backfillIndexData;
    @XmlElement(name = "DirectAdService", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected DirectAdService directAdService;
    @XmlElement(name = "Backfills", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected Backfills backfills;
    @XmlElement(name = "RequestHeaders", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected RequestHeaders requestHeaders;
    @XmlElement(name = "ApplicationResponseTime", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected ApplicationResponseTime applicationResponseTime;

    /**
     * Gets the value of the build property.
     * 
     * @return
     *     possible object is
     *     {@link Build }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public Build getBuild() {
        return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *     allowed object is
     *     {@link Build }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setBuild(Build value) {
        this.build = value;
    }

    /**
     * Gets the value of the hostInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HostInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public HostInfo getHostInfo() {
        return hostInfo;
    }

    /**
     * Sets the value of the hostInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setHostInfo(HostInfo value) {
        this.hostInfo = value;
    }

    /**
     * Gets the value of the rankModel property.
     * 
     * @return
     *     possible object is
     *     {@link RankModel }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public RankModel getRankModel() {
        return rankModel;
    }

    /**
     * Sets the value of the rankModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RankModel }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRankModel(RankModel value) {
        this.rankModel = value;
    }

    /**
     * Gets the value of the feedAndSubPublisherInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FeedAndSubPublisherInformation }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public FeedAndSubPublisherInformation getFeedAndSubPublisherInformation() {
        return feedAndSubPublisherInformation;
    }

    /**
     * Sets the value of the feedAndSubPublisherInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedAndSubPublisherInformation }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setFeedAndSubPublisherInformation(FeedAndSubPublisherInformation value) {
        this.feedAndSubPublisherInformation = value;
    }

    /**
     * Gets the value of the backfillIndexData property.
     * 
     * @return
     *     possible object is
     *     {@link BackfillIndexData }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public BackfillIndexData getBackfillIndexData() {
        return backfillIndexData;
    }

    /**
     * Sets the value of the backfillIndexData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackfillIndexData }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setBackfillIndexData(BackfillIndexData value) {
        this.backfillIndexData = value;
    }

    /**
     * Gets the value of the directAdService property.
     * 
     * @return
     *     possible object is
     *     {@link DirectAdService }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public DirectAdService getDirectAdService() {
        return directAdService;
    }

    /**
     * Sets the value of the directAdService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectAdService }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setDirectAdService(DirectAdService value) {
        this.directAdService = value;
    }

    /**
     * Gets the value of the backfills property.
     * 
     * @return
     *     possible object is
     *     {@link Backfills }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public Backfills getBackfills() {
        return backfills;
    }

    /**
     * Sets the value of the backfills property.
     * 
     * @param value
     *     allowed object is
     *     {@link Backfills }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setBackfills(Backfills value) {
        this.backfills = value;
    }

    /**
     * Gets the value of the requestHeaders property.
     * 
     * @return
     *     possible object is
     *     {@link RequestHeaders }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public RequestHeaders getRequestHeaders() {
        return requestHeaders;
    }

    /**
     * Sets the value of the requestHeaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestHeaders }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRequestHeaders(RequestHeaders value) {
        this.requestHeaders = value;
    }

    /**
     * Gets the value of the applicationResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationResponseTime }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public ApplicationResponseTime getApplicationResponseTime() {
        return applicationResponseTime;
    }

    /**
     * Sets the value of the applicationResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationResponseTime }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setApplicationResponseTime(ApplicationResponseTime value) {
        this.applicationResponseTime = value;
    }

}
