//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.22 at 10:01:12 AM PDT 
//


package com.sendori.testcenter.xsd;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:lookSmartResults}ssResultSet"/>
 *         &lt;element ref="{}RejectedAds"/>
 *         &lt;element ref="{}ExpandedMatchInfo"/>
 *         &lt;element ref="{}CategoryMatchInfo"/>
 *         &lt;element ref="{}RejectedAdGroups"/>
 *         &lt;element ref="{}RejectedCampaigns"/>
 *         &lt;element ref="{}Debug"/>
 *         &lt;element ref="{}ResponseTimeDebug"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ssResultSet",
    "rejectedAds",
    "expandedMatchInfo",
    "categoryMatchInfo",
    "rejectedAdGroups",
    "rejectedCampaigns",
    "debug",
    "responseTimeDebug"
})
@XmlRootElement(name = "lookSmartResults", namespace = "urn:lookSmartResults")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class LookSmartResults {

    @XmlElement(namespace = "urn:lookSmartResults", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected SsResultSet ssResultSet;
    @XmlElement(name = "RejectedAds", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected RejectedAds rejectedAds;
    @XmlElement(name = "ExpandedMatchInfo", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected ExpandedMatchInfo expandedMatchInfo;
    @XmlElement(name = "CategoryMatchInfo", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected CategoryMatchInfo categoryMatchInfo;
    @XmlElement(name = "RejectedAdGroups", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected RejectedAdGroups rejectedAdGroups;
    @XmlElement(name = "RejectedCampaigns", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected RejectedCampaigns rejectedCampaigns;
    @XmlElement(name = "Debug", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected Debug debug;
    @XmlElement(name = "ResponseTimeDebug", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected ResponseTimeDebug responseTimeDebug;

    /**
     * Gets the value of the ssResultSet property.
     * 
     * @return
     *     possible object is
     *     {@link SsResultSet }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public SsResultSet getSsResultSet() {
        return ssResultSet;
    }

    /**
     * Sets the value of the ssResultSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SsResultSet }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setSsResultSet(SsResultSet value) {
        this.ssResultSet = value;
    }

    /**
     * Gets the value of the rejectedAds property.
     * 
     * @return
     *     possible object is
     *     {@link RejectedAds }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public RejectedAds getRejectedAds() {
        return rejectedAds;
    }

    /**
     * Sets the value of the rejectedAds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RejectedAds }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRejectedAds(RejectedAds value) {
        this.rejectedAds = value;
    }

    /**
     * Gets the value of the expandedMatchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExpandedMatchInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public ExpandedMatchInfo getExpandedMatchInfo() {
        return expandedMatchInfo;
    }

    /**
     * Sets the value of the expandedMatchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpandedMatchInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setExpandedMatchInfo(ExpandedMatchInfo value) {
        this.expandedMatchInfo = value;
    }

    /**
     * Gets the value of the categoryMatchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryMatchInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public CategoryMatchInfo getCategoryMatchInfo() {
        return categoryMatchInfo;
    }

    /**
     * Sets the value of the categoryMatchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryMatchInfo }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setCategoryMatchInfo(CategoryMatchInfo value) {
        this.categoryMatchInfo = value;
    }

    /**
     * Gets the value of the rejectedAdGroups property.
     * 
     * @return
     *     possible object is
     *     {@link RejectedAdGroups }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public RejectedAdGroups getRejectedAdGroups() {
        return rejectedAdGroups;
    }

    /**
     * Sets the value of the rejectedAdGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link RejectedAdGroups }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRejectedAdGroups(RejectedAdGroups value) {
        this.rejectedAdGroups = value;
    }

    /**
     * Gets the value of the rejectedCampaigns property.
     * 
     * @return
     *     possible object is
     *     {@link RejectedCampaigns }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public RejectedCampaigns getRejectedCampaigns() {
        return rejectedCampaigns;
    }

    /**
     * Sets the value of the rejectedCampaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link RejectedCampaigns }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRejectedCampaigns(RejectedCampaigns value) {
        this.rejectedCampaigns = value;
    }

    /**
     * Gets the value of the debug property.
     * 
     * @return
     *     possible object is
     *     {@link Debug }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public Debug getDebug() {
        return debug;
    }

    /**
     * Sets the value of the debug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Debug }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setDebug(Debug value) {
        this.debug = value;
    }

    /**
     * Gets the value of the responseTimeDebug property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseTimeDebug }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public ResponseTimeDebug getResponseTimeDebug() {
        return responseTimeDebug;
    }

    /**
     * Sets the value of the responseTimeDebug property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseTimeDebug }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setResponseTimeDebug(ResponseTimeDebug value) {
        this.responseTimeDebug = value;
    }

}
