//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.22 at 10:01:12 AM PDT 
//


package com.sendori.testcenter.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import java.math.BigDecimal;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.examples.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Title_QNAME = new QName("urn:lookSmartResults", "title");
    private final static QName _Abstract_QNAME = new QName("urn:lookSmartResults", "abstract");
    private final static QName _DisplayUrl_QNAME = new QName("urn:lookSmartResults", "displayUrl");
    private final static QName _Cpc_QNAME = new QName("urn:lookSmartResults", "cpc");
    private final static QName _Url_QNAME = new QName("urn:lookSmartResults", "url");
    private final static QName _OriginalDestinationUrl_QNAME = new QName("", "OriginalDestinationUrl");
    private final static QName _AdType_QNAME = new QName("", "AdType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.examples.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RejectedCampaigns }
     * 
     */
    public RejectedCampaigns createRejectedCampaigns() {
        return new RejectedCampaigns();
    }

    /**
     * Create an instance of {@link ResponseTimeDebug }
     * 
     */
    public ResponseTimeDebug createResponseTimeDebug() {
        return new ResponseTimeDebug();
    }

    /**
     * Create an instance of {@link RequestHeaders }
     * 
     */
    public RequestHeaders createRequestHeaders() {
        return new RequestHeaders();
    }

    /**
     * Create an instance of {@link SsResultSet }
     * 
     */
    public SsResultSet createSsResultSet() {
        return new SsResultSet();
    }

    /**
     * Create an instance of {@link AdGroup }
     * 
     */
    public AdGroup createAdGroup() {
        return new AdGroup();
    }

    /**
     * Create an instance of {@link FeedAndSubPublisherInformation }
     * 
     */
    public FeedAndSubPublisherInformation createFeedAndSubPublisherInformation() {
        return new FeedAndSubPublisherInformation();
    }

    /**
     * Create an instance of {@link Ad }
     * 
     */
    public Ad createAd() {
        return new Ad();
    }

    /**
     * Create an instance of {@link SsResult }
     * 
     */
    public SsResult createSsResult() {
        return new SsResult();
    }

    /**
     * Create an instance of {@link Campaign }
     * 
     */
    public Campaign createCampaign() {
        return new Campaign();
    }

    /**
     * Create an instance of {@link HostInfo }
     * 
     */
    public HostInfo createHostInfo() {
        return new HostInfo();
    }

    /**
     * Create an instance of {@link RankModel }
     * 
     */
    public RankModel createRankModel() {
        return new RankModel();
    }

    /**
     * Create an instance of {@link CategoryMatchInfo }
     * 
     */
    public CategoryMatchInfo createCategoryMatchInfo() {
        return new CategoryMatchInfo();
    }

    /**
     * Create an instance of {@link DedupedAds }
     * 
     */
    public DedupedAds createDedupedAds() {
        return new DedupedAds();
    }

    /**
     * Create an instance of {@link Debug }
     * 
     */
    public Debug createDebug() {
        return new Debug();
    }

    /**
     * Create an instance of {@link LookSmart }
     * 
     */
    public LookSmart createLookSmart() {
        return new LookSmart();
    }

    /**
     * Create an instance of {@link BackfillIndexData }
     * 
     */
    public BackfillIndexData createBackfillIndexData() {
        return new BackfillIndexData();
    }

    /**
     * Create an instance of {@link TimeDistribution }
     * 
     */
    public TimeDistribution createTimeDistribution() {
        return new TimeDistribution();
    }

    /**
     * Create an instance of {@link ExpandedMatchInfo }
     * 
     */
    public ExpandedMatchInfo createExpandedMatchInfo() {
        return new ExpandedMatchInfo();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link LookSmartResults }
     * 
     */
    public LookSmartResults createLookSmartResults() {
        return new LookSmartResults();
    }

    /**
     * Create an instance of {@link DirectAdService }
     * 
     */
    public DirectAdService createDirectAdService() {
        return new DirectAdService();
    }

    /**
     * Create an instance of {@link BackfillDistributionTime }
     * 
     */
    public BackfillDistributionTime createBackfillDistributionTime() {
        return new BackfillDistributionTime();
    }

    /**
     * Create an instance of {@link ApplicationResponseTime }
     * 
     */
    public ApplicationResponseTime createApplicationResponseTime() {
        return new ApplicationResponseTime();
    }

    /**
     * Create an instance of {@link RejectedAdGroups }
     * 
     */
    public RejectedAdGroups createRejectedAdGroups() {
        return new RejectedAdGroups();
    }

    /**
     * Create an instance of {@link Backfills }
     * 
     */
    public Backfills createBackfills() {
        return new Backfills();
    }

    /**
     * Create an instance of {@link DirectAdDistributionTime }
     * 
     */
    public DirectAdDistributionTime createDirectAdDistributionTime() {
        return new DirectAdDistributionTime();
    }

    /**
     * Create an instance of {@link RunofNetworkDistributionTime }
     * 
     */
    public RunofNetworkDistributionTime createRunofNetworkDistributionTime() {
        return new RunofNetworkDistributionTime();
    }

    /**
     * Create an instance of {@link RejectedAds }
     * 
     */
    public RejectedAds createRejectedAds() {
        return new RejectedAds();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link PhaseDistribution }
     * 
     */
    public PhaseDistribution createPhaseDistribution() {
        return new PhaseDistribution();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:lookSmartResults", name = "title")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:lookSmartResults", name = "abstract")
    public JAXBElement<String> createAbstract(String value) {
        return new JAXBElement<String>(_Abstract_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:lookSmartResults", name = "displayUrl")
    public JAXBElement<String> createDisplayUrl(String value) {
        return new JAXBElement<String>(_DisplayUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:lookSmartResults", name = "cpc")
    public JAXBElement<BigDecimal> createCpc(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Cpc_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:lookSmartResults", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginalDestinationUrl")
    public JAXBElement<String> createOriginalDestinationUrl(String value) {
        return new JAXBElement<String>(_OriginalDestinationUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AdType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdType(String value) {
        return new JAXBElement<String>(_AdType_QNAME, String.class, null, value);
    }

}
