//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.22 at 10:01:12 AM PDT 
//


package com.sendori.testcenter.xsd;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LookSmart"/>
 *         &lt;element ref="{}ApplicationResponseTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RunofNetworkServiceTime" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lookSmart",
    "applicationResponseTime"
})
@XmlRootElement(name = "RunofNetworkDistributionTime")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class RunofNetworkDistributionTime {

    @XmlElement(name = "LookSmart", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected LookSmart lookSmart;
    @XmlElement(name = "ApplicationResponseTime", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected ApplicationResponseTime applicationResponseTime;
    @XmlAttribute(name = "RunofNetworkServiceTime", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected BigInteger runofNetworkServiceTime;

    /**
     * Gets the value of the lookSmart property.
     * 
     * @return
     *     possible object is
     *     {@link LookSmart }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public LookSmart getLookSmart() {
        return lookSmart;
    }

    /**
     * Sets the value of the lookSmart property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookSmart }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setLookSmart(LookSmart value) {
        this.lookSmart = value;
    }

    /**
     * Gets the value of the applicationResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationResponseTime }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public ApplicationResponseTime getApplicationResponseTime() {
        return applicationResponseTime;
    }

    /**
     * Sets the value of the applicationResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationResponseTime }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setApplicationResponseTime(ApplicationResponseTime value) {
        this.applicationResponseTime = value;
    }

    /**
     * Gets the value of the runofNetworkServiceTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public BigInteger getRunofNetworkServiceTime() {
        return runofNetworkServiceTime;
    }

    /**
     * Sets the value of the runofNetworkServiceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-22T10:01:12-07:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setRunofNetworkServiceTime(BigInteger value) {
        this.runofNetworkServiceTime = value;
    }

}
